compressionLevel: mixed

enableGlobalCache: false

httpRetry: 5

httpTimeout: 60000

nmHoistingLimits: workspaces

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x86
    - arm64
  os:
    - linux
    - darwin
    - current

yarnPath: .yarn/releases/yarn-3.6.0.cjs
